
---
# All possible units and unit conversions are outlined in scripts/quantities.js
# Adding the suffix .Max or .Min to any JSON source will give you the maximum or minimum value over time.
# Adding the suffix .Neg to any JSON source will negate the incoming value.

  - type: Layout
    columns:
      - id: column1
        width: 25%
      - id: column2
        width: 75%
        columns:
          - id: column2_a
            width: 100%
          - id: column2_b
            width: 50%
          - id: column2_c
            width: 50%

  - id: Stats
    type: Text
    height: 125
    column: column1
    controls:
      - label: Incoming Packets
        source: Stats.PacketsReceivedRecently
      - label: Incoming Total
        source: Stats.PacketsReceivedTotal
      - label: Lost Total
        source: Stats.PacketsLostTotal
      - label: Last Packet Rcvd
        source: Stats.TimeLastPacketReceived

  - id: GPS Status
    type: Text
    height: 125
    column: column1
    controls:
      - label: NavMode
        source: GPS1.NavMode
      - label: Satellites
        source: GPS1.NumOfSats
        
  - id: GPS
    type: Text
    height: 125
    column: column1
    controls:
      - label: Lat
        source: GPS1.Latitude
        units: deg
      - label: Long
        source: GPS1.Longitude
        units: deg
      - label: Height
        source: GPS1.Height
        units: m
      - label: Max Height
        source: GPS1.Height.Max
        units: m
        
  - id: Acceleration
    type: Text
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.AccelerometerX
        units: m/s^2
      - label: Y
        source: ADIS.AccelerometerY
        units: m/s^2
      - label: Z
        source: ADIS.AccelerometerZ
        units: m/s^2
      - label: Magnitude
        source: ADIS.AccelerometerMagn
        units: gee
        
  - id: Z-Roll
    type: LineGraph
    width: 600
    height: 320
    column: column2_a
    maxDataSize: Number.MAX_VALUE
    controls:
      - label: Z Roll
        source: ADIS.GyroscopeX
        units: deg/sec
        
  - id: Altitude
    type: Gauge
    label: Altitude
    size: 250
    column: column2_b
    minorTicks: 5
    max: 10000
    yellowPercent: 80
    redPercent: 90
    controls:
      - label: Height
        source: GPS1.Height
        units: m

  - id: Gyroscrope
    type: Text
    height: 125
    column: column2_c
    controls:
      - label: X
        source: ADIS.GyroscopeX
        units: deg/sec
      - label: Y
        source: ADIS.GyroscopeY
        units: deg/sec
      - label: Z
        source: ADIS.GyroscopeZ
        units: deg/sec
      - label: Magnitude
        source: ADIS.GyroscopeMagn
        units: deg/sec
        