---
# All possible units and unit conversions are outlined in scripts/quantities.js
# Adding the suffix .Max or .Min to any JSON source will give you the maximum or minimum value over time.
# Adding the suffix .Neg to any JSON source will negate the incoming value.

  - type: Layout
    columns:
      - id: column1
        width: 25%
      - id: column2
        width: 70%

  - id: GPS Status
    type: Text
    width: 200
    height: 125
    column: column1
    controls:
      - label: NavMode
        source: "GPS\x01.NavMode"
      - label: Satellites
        source: "GPS\x01.NumOfSats"
        
  - id: GPS
    type: Text
    width: 200
    height: 125
    column: column1
    controls:
      - label: Lat
        source: "GPS\x01.Latitude"
        units: deg
      - label: Long
        source: "GPS\x01.Longitude"
        units: deg
      - label: Height
        source: "GPS\x01.Height"
        units: m
      - label: Max Height
        source: "GPS\x01.Height.Max"
        units: m
        
  - id: Acceleration
    type: Text
    width: 200
    height: 125
    column: column1
    controls:
      - label: X
        source: ADIS.AccelerometerX
        units: m/s^2
      - label: Y
        source: ADIS.AccelerometerY
        units: m/s^2
      - label: Z
        source: ADIS.AccelerometerZ
        units: m/s^2
      - label: Magnitude
        source: ADIS.AccelerometerMagn
        units: gee
        
  - id: Z-Roll
    type: LineGraph
    width: 600
    height: 320
    column: column2
    maxDataSize: Number.MAX_VALUE
    controls:
      - label: Z Roll
        source: ADIS.GyroscopeX
        units: deg/sec
        
  - id: Altitude
    type: Gauge
    label: Altitude
    size: 250
    column: column2
    minorTicks: 5
    max: 10000
    yellowPercent: 80
    redPercent: 90
    controls:
      - label: Height
        source: "GPS\x01.Height"
        units: m
